### PR TITLE
Add Selectors (level 4)

### PR DESCRIPTION
**Pull request by cvrebert**

### CODE REVIEW

**Comment by annevk** [comment]
1. It should be https://drafts.csswg.org/selectors/
2. It should replace the current reference

**Comment by cvrebert** [comment]
> 2\. It should replace the current reference

So then why are there entries for both Media Queries levels 3 and 4?

**Comment by cvrebert** [comment]
Also, what should I do about the caniuse and HTML5Please links, which are Level 3-specific?

**Comment by annevk** [comment]
I tend to think we should have one link for Media Queries too. Whatever version is latest and being implemented.

I guess if the HTML5Please & caniuse don't have a latest link, you point to whatever they do have (level 3).

Asked @sideshowbarker to chime in since he's managing this page.

**Comment by annevk** [comment]
Oh, @sideshowbarker agrees with me: http://krijnhoetmer.nl/irc-logs/whatwg/20150731#l-164. I guess that's settled then.

He suggests you talk to @Fyrd about updating caniuse.

**Comment by cvrebert** [comment]
> I guess if the HTML5Please & caniuse don't have a latest link, you point to whatever they do have (level 3).

That's reasonable for caniuse, but putting the green "HTML5Please recommends as ready to use" flag for a different level of the spec just seems misleading.

**Comment by annevk** [comment]
Yeah, but I guess there'll always be some of that at such a high level.

**Comment by annevk** [comment]
Not sure why this went different: https://github.com/whatwg/platform.html5.org/commit/42a670e62dadeb2c7f467374908d224429ae46f3

**Pull request closed without merging**
