### PR TITLE
Meta: enable HTML checker

### PR DESCRIPTION
**Pull request by annevk**

### CODE REVIEW

**Comment by annevk** [comment]
@sideshowbarker I guess we need to decide whether those resources you checked in need to be preserved and excluded from validation or whether we need to fix them. It seems this has found a bunch of legitimate errors too though that are worth fixing.

**Comment by annevk** [comment]
(I'm happy to fix all errors, but want your opinion first.)

**Comment by sideshowbarker** [comment]
I think we should skip checking of everything in the `webapps` and `workers` subdirectories, but fix any errors in the root `index.html` file and https://github.com/whatwg/platform.html5.org/blob/master/specs/index.html and https://github.com/whatwg/platform.html5.org/blob/master/history/index.html

**Comment by annevk** [comment]
@sideshowbarker maybe you can provide the fix for .travis.yml that makes it skip those directories?

**Comment by sideshowbarker** [comment]
> @sideshowbarker maybe you can provide the fix for .travis.yml that makes it skip those directories?

yes (assigning to myself)

**Comment by annevk** [comment]
@sideshowbarker ping.

**Comment by sideshowbarker** [comment]
Will get back to this asap (this weekend)

**Pull request merged**
